
export const enum Actions {
  init = '@@INIT',
  initAsync = '@@INIT (async)',
  afterInitUpdate = 'After Init Update',
  paused = '|| <PAUSED> ||',
  unpause = '>> UNPAUSE >>',
  loading = 'LOADING...',
  hardResetting = 'HARD RESETTING !!!',
  update = 'Update',
  updateAll = 'Update All',
  set = 'Set',
  add = 'Add',
  remove = 'Remove',
  removeRange = 'Remove Range',
  delete = 'Delete',
  clear = 'Clear',
  reset = 'Reset',
  error = '**ERROR** :(',
  destroy = '@@DESTROY',
}
